### ISSUE TITLE
Navigationbar ist im Widescreenmodus nicht mehr Widescreen

### ISSUE THREAD

**Issue by therandomguy42** [Scarwolf/p0weruser#100]
## Allgemeine Informationen
**Browser:** Chrome|Firefox
Chrome

**Version:** Version des UserScripts
2.2.0

**Modul:** Wenn du weißt, welches Modul das Problem auslöst, so nenne dieses hier.
StyleCustomization: off
WidescreenMode: on

## Fehlerbeschreibung
> Navigationbar ist im Widescreenmodus nicht mehr auf die gesammte Bildschirmweite ausgebreitet.

## Aktuelles Verhalten
> Die Navigationbar ist aktuell zentriert wie bei dem normal pr0 design.

## Erwartetes Verhalten
> Die Navigationbar sollte sich, wie vorher, im Widescreenmodus auf die gesammte Bildschirmweite ausbreiten.

## Reproduzierbarkeit
> Stilisierung ausschalten, Widescreenmodus einschalten und auf new oder beliebt gehen.

**Comment by twobiers** [comment]
War ne dumme Änderung, fix kommt alsbald.
