### ISSUE TITLE
Zoom in im Widescreen mode funktioniert nicht

### ISSUE THREAD

**Issue by w00kee** [Scarwolf/p0weruser#103]
## Bug Summary / Fehlerbeschreibung
Im Widescreenmode kann nicht in Bilder hereingezoomt werden mit der zugehörigen Taste.

## Steps to Reproduce the Problem / Wie kann der Fehler reproduziert werden

  1.Widescreenmode aktivieren
  1.Zoom in Taste bei aufgerufenem post klicken
  Bug:
  Zoom in wird nicht ausgeführt
  Scrollen führt weiterhin zum Post Wechsel.

## Specifications / Daten

  - Version:
  - Browser: Brave v 1.41.100
  - Active p0weruser Modules: Stilisierung Erweiterte Komentare Benis in der Navigation,Texterkennung, Widescreenmode

**Comment by Yougoshatenshi** [comment]
Leertaste als Shortcut funktioniert weiterhin, als Workaround.

**Comment by twobiers** [comment]
Müsste wieder gehen
