### ISSUE TITLE
Diverse Anzeigeprobleme

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [Scarwolf/p0weruser#104]
![image](https://user-images.githubusercontent.com/627469/184257366-8f75ac3b-21fa-4e91-b8de-91b76d1c6c77.png)

Seit ein paar Patches ist einiges falsch.
Das Front-Div hört einfach so unten auf, das Nachrichtenpopup ist ganz rechts und schliesst sich nur nach 2-3 Klicks irgendwo in das Fenster, was nervt, wenn man kurz ein Kommentar verfassen will und kein TAB -> Space machen kann, weil das Popup dann erst geschlossen wird, bevor man mit weiteren Space-Taps das Kommentar absenden kann.

Auch hatte ich schon einige Male den Fall, dass der Counter der Nachrichten falsch ist. Ich habe die Vermutung, dass eventuell etwas falsch gecached wird, da ab und zu z. B. 2 neue Benachrichtigungen da sein sollen, aber nur eine neue Benachrichtigung gehighlightet wird, aber dann später eine weitere zwischen den anderen auftaucht. Es mag sein, dass ich da etwas mal übersehen habe, aber es ist nun mehrfach passiert. Lässt sich leider schwer festhalten oder live prüfen.

Edit:
![image](https://user-images.githubusercontent.com/627469/184258306-f71042c0-a64c-44d7-b3c4-3d26207558e9.png)
Das da scheint ein Anzeiger dafür zu sein, dass das Script versucht etwas zu laden? Bei Suchen mit wenigen Ergebnissen rastet diese Anzeige zumindest hart aus und zumindest im Taskmanager habe ich dann beim pr0 eine sehr hohe Auslastung in Sachen RAM und Netzwerkverbrauch

**Comment by twobiers** [comment]
Die angesprochenen Darstellungsfehler kriege ich weder in Firefox noch in Chrome reproduziert. 
Dass das Nachrichtenpopup ganz rechts ist, ist so für den Widescreen Mode gedacht, weil da die Navbar anders aussieht - ich schau mal ob ich da ne bessere Kompatibilität hinbekomme.

Der letzte Fehler ist gar nicht gut, ich versuch da so schnell wie möglich was zu finden. 

Entschuldige die Probleme in letzter Zeit, ich hatte ne Menge mit den Scrollbars zu kämpfen und hab die mit dem letzten Update rausgeworfen. In Zukunft sollte das wieder stabiler werden.

**Comment by twobiers** [comment]
Der letzte Fehler ist für mich repoduzierbar und betrifft das "Rep0st" Modul, sobald man im Notification-Center auf eine Nachricht klickt.
Ich versuche das heute noch zu beheben - im Zweifel aber einfach Rep0st Modul deaktivieren, sollte Abhilfe schaffen.

**Comment by AkumaNoTsubasa** [comment]
Der Darstellungsfehler kommt, wenn man einen Post durch eine Benachrichtigung aufruft. Und wäre nett, wenn das Benachrichtigungsfenster beim Button bleibt und nicht irgendwo anders aufploppt und sich beim anklicken eines Posts auch wieder killt.

Premium wäre übrigens, wenn nur Benachrichtigungen als "Gelesen" markiert werden, wenn man sie angeklickt hat bzw. nur die Benachrichtigungen dieses einen Posts als gelesen markiert werden, so dass man einzelne Posts zwischen einem Beliebt-Benachrichtigungsspam leichter findet.

**Comment by twobiers** [comment]
Ah ja, perfekt danke. Dann kümmer ich mich jetzt drum.

> Premium wäre übrigens, wenn nur Benachrichtigungen als "Gelesen" markiert werden, wenn man sie angeklickt hat bzw. nur die Benachrichtigungen dieses einen Posts als gelesen markiert werden, so dass man einzelne Posts zwischen einem Beliebt-Benachrichtigungsspam leichter findet.

Wäre eine größere Änderung. Wäre cool, ja - gibt die API aber nicht her, man müsste das also irgendwie selbst implementieren und damit auch wieder deutlich fehleranfälliger.

**Comment by twobiers** [comment]
Am einfachsten wäre es, das Notification Center zu schließen, wenn auf eine Benachrichtigung geklickt wird. Wäre das ein akzeptabler Weg?

**Comment by AkumaNoTsubasa** [comment]
> Wäre eine größere Änderung. Wäre cool, ja - gibt die API aber nicht her, man müsste das also irgendwie selbst implementieren und damit auch wieder deutlich fehleranfälliger.

Ach, brauchst doch nur die Post-ID nehmen und die als "Gelesen" nehmen. Sollte nicht wirklich problematisch sein.

> Am einfachsten wäre es, das Notification Center zu schließen, wenn auf eine Benachrichtigung geklickt wird. Wäre das ein akzeptabler Weg?
Ja, das wär super.

**Comment by twobiers** [comment]
Mit dem nächsten Release sollten alle Fehler behoben werden. Für deinen Vorschlag hab ich #105 erstellt.
