### ISSUE TITLE
Benis verstecken

### ISSUE THREAD

**Issue by rottenpuppy** [Scarwolf/p0weruser#106]
## Allgemeine Informationen
**Browser:** Firefox

**Version:** Alle

**Modul:** Benis

## Beschreibung
Moin, wäre geil wenn ihr einen Schalter einführt, der den Benis bei Posts und Kommentaren deaktiviert. Thx

**Comment by twobiers** [comment]
Kommt mit dem nächsten Release. Ist in dem "Stilisierung" Modul und versteckt den Benis, indem die Schrift transparent gerendert wird. Der Benis ist weiterhin da und kann über bspw. textmarkierung sichtbar gemacht werden. Alles andere, was mir in dem Kopf kam, wäre eine zu invasive Änderung gewesen.

**Comment by rottenpuppy** [comment]
Teste das aus wenn ich Zeit hab, sage schonmal danke für die Änderung :*Am 01.10.2022 um 15:45 schrieb Tobi ***@***.***>:﻿
Kommt mit dem nächsten Release. Ist in dem "Stilisierung" Modul und versteckt den Benis, indem die Schrift transparent gerendert wird. Der Benis ist weiterhin da und kann über bspw. textmarkierung sichtbar gemacht werden. Alles andere, was mir in dem Kopf kam, wäre eine zu invasive Änderung gewesen.
