### ISSUE TITLE
Script funktioniert leider nicht bei mir

### ISSUE THREAD

**Issue by gametabe** [Scarwolf/p0weruser#107]
## Steps to Reproduce the Problem / Wie kann der Fehler reproduziert werden

  1. Keine Ahnung, der is halt einfach da xD
  
## Specifications / Daten

  - Version: `2.3.1`
  - Browser: `Opera v. 90.0.4480.78`
  - Active p0weruser Modules: `alle?`

![Bild_2022-09-05_183016099](https://user-images.githubusercontent.com/81835190/188489516-50fa536c-7acc-4e98-a332-aba0dcb80f4c.png)

**Comment by twobiers** [comment]
Geh in die Einstellungen, da sollte ein Reiter "p0weruser" sein.

**Comment by gametabe** [comment]
ohh fuck, da war ja was, danke für deine hilfe 🤦‍♂️🤣
