### ISSUE TITLE
Allow to disable keyboard shortcuts

### ISSUE THREAD

**Issue by Lokke** [Scarwolf/p0weruser#111]
Buttons 1, 2, 3 are linked to /new/, /top/ and /stelz/, which brings the annoying behavior that when trying to jump to position 10%, 20% or 30% within a video, the post gets closed. 
It would be great if this could be disabled.

**Comment by twobiers** [comment]
p0weruser does not bind the number keys. Do you have any other extension or userscript active? 
Also please adhere to the [bug report template](https://github.com/Scarwolf/p0weruser/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md).

**Comment by Lokke** [comment]
NVM - shortcuts belong to https://github.com/Frubi22/selfmade_m0d
