### ISSUE TITLE
"Transparente Navigationsleiste" lässt sich nicht abschalten

### ISSUE THREAD

**Issue by Awebb** [Scarwolf/p0weruser#112]
## Bug Summary / Fehlerbeschreibung

Ich kann "Transparente Navigationsleiste" nicht deaktivieren und somit auch das Zentrieren nicht loswerden. (Warum ist das ein Schalter? :-O)

## Steps to Reproduce the Problem / Wie kann der Fehler reproduziert werden

  1. Einstellungssymbol
  1. p0weruser-Tab
  1. Haken bei "Transparente Navigationsleiste" raus
  1. Nach unten Scrollen und "Einstellungen speichern"
  1. pr0 im Browser refreshen

  Anmerkung: Das "Stilisierung"-Modul komplett zu deaktivieren behebt das Problem.

## Specifications / Daten

  - Version: 2.3.1
  - Browser: Firefox 105.3 (Fehler trat schon früher auf)
  - Active p0weruser Modules: Stilisierung, Erweiterte Kommentare, Benis in Navigation, Filtermarkierung, Texterkennung, Rep0st Check, Repost Markierung, Link to Statistics, "Bereits gesehen"-Markierung, Pr0p0ll Integration, Widescreen Mode

**Comment by twobiers** [comment]
Upsi, Bugfix kommt mit dem nächsten Release. 
Nur zur Vorwarnung: Das Widescreen Modul setzt standardmäßig auch einen halb-transparenten Hintergrund.

Hier die transparente Navbar aus dem Stilisierung Modul:
![image](https://user-images.githubusercontent.com/22715034/194833576-338713d0-5f94-484f-8bdb-8058d37e9eb4.png)

Hier aus dem Widescreen-Modul
![image](https://user-images.githubusercontent.com/22715034/194833708-76876009-7caa-408f-ac8e-a81f920dd547.png)
