### ISSUE TITLE
Script stopped working altogether

### ISSUE THREAD

**Issue by Kraechtshammer** [Scarwolf/p0weruser#114]
## Bug Summary / Fehlerbeschreibung
The script suddenly stopped working for me altogether at around 8pm on 11.10.2022. I was on the site, opened a post in another window and noticed widescreen mode was gone there. Then I noticed that it's disappeared from settings. It was working when the session started though. This issue persists on both Firefox and Chrome with everything on latest version, with any other blockers disabled for the site. I have tried reinstalling the script, removing and installing, restarting the browser and computer.

**Comment by twobiers** [comment]
Yes, it's my fault. I'm working on it.

**Comment by Kraechtshammer** [comment]
Oops that wasn't supposed to get closed just yet!

**Comment by twobiers** [comment]
Should work again.
