### ISSUE TITLE
Scrollen geht nicht mehr + div. anderes

### ISSUE THREAD

**Issue by Davai0** [Scarwolf/p0weruser#115]
## Bug Summary / Fehlerbeschreibung
Nach dem Update von vorhin geht das scrollen nicht mehr richtig mit dem Mausrad. 1 oder 2 Bilder lang geht es und dann hängt es sich auf. Hab kurz vorher auf die Lupe links oben bei einem Bild gedrückt. Liegt es vielleicht daran? Reboot hat nichts gebracht.
Ebenfalls könnte ich schwören man konnte Uploads schließen indem man links oder rechts daneben geklickt hat (und nicht direkt drauf) - geht auch nicht mehr. Das Vergrößerungssymbol rechts oben (nicht das Standard pr0 Blus) ist auch nicht mehr klickbar. Stattdessen gehts einfach rechts zum nächsten Bild weiter.

## Steps to Reproduce the Problem / Wie kann der Fehler reproduziert werden

  1. Gehe auf ein Bild / Video
  1. Scrolle weiter
  1. Hängt sich beim 2. oder 3. Bild auf und scrollt nicht weiter.

## Specifications / Daten

  - Version: 2.4.1
  - Browser: Chrome
  - Active p0weruser Modules: Widescreenmode?

**Comment by twobiers** [comment]
Die Fehler sind bekannt und sollten in der Dev-Version behoben sein. Du kannst das ja mal testen und gucken, dann Release ich das. 

https://scarwolf.github.io/p0weruser/p0weruser.dev.user.js

**Comment by twobiers** [comment]
Das mit dem daneben klicken muss ich mir nochmal anschauen, das hab ich in den letzten fixes nicht explizit gemacht könnte aber ein Nebeneffekt gewesen sein.

**Comment by twobiers** [comment]
Hab's kurz geprüft. Bei mir geht alles in der Dev-Version. Wenn man die Maximize-Funktion nutzt, verschieben sich die vor/zurück pfeile etwas, aber das ist nur ein Schönheitsproblem und schränkt die Funktionalität nicht ein. Behebt sich von alleine, wenn man einen Post weiter geht. 

Ich release die Version jetzt, dann sollte das erledigt sein. Hoffe das behebt es auch bei dir.

**Comment by Davai0** [comment]
Wurde alles behoben, danke.
