### ISSUE TITLE
perma dauerload mit RAM Überlastung

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [Scarwolf/p0weruser#118]
https://drive.google.com/file/d/1vjX4U4f-t_Nz_Xmb_u9PvJf_-DpehVB7/view

Hatte das schon mal angemerkt. Der kleine Balken unter dem Menüzeichen zeigt ja an, dass etwas geladen wird und ab und zu lädt er und hört nicht auf. Wenn man das einfach mal 2 Stunden so passieren lässt, crasht das Tab wegen RAM Überladung.

**Comment by twobiers** [comment]
Hast du das rep0st Modul in Verwendung? Ich hab das in Verdacht.
Kannst du ggf. Mal vorübergehend ausschalten und gucken ob der Fehler weiterhin Auftritt.

**Comment by AkumaNoTsubasa** [comment]
Die beiden Rep0st Features deaktiviert, nu ists weg, yup

**Comment by twobiers** [comment]
Ich kriege den Bug jetzt endlich reproduziert - einen Fix dafür habe ich aber noch nicht. Das ursächliche Problem liegt (wie immer) im Widescreen Modul.

1. pr0 aufrufen
2. Einstellungen aufrufen
3. Scrollen

Scheinbar verhakt sich der onscroll handler und versucht permanent ältere Posts abzufragen, bis das Ende vom Stream erreicht ist. Schätze, dass die View vom Stream nicht ordentlich geschlossen wird.

**Comment by AkumaNoTsubasa** [comment]
Das passiert an vielen Enden. Auch bei Suchen bei denen keine andern Posts mehr vorhanden sind. Ab und zu auch, wenn ein Post offen ist.

**Comment by twobiers** [comment]
Das ist ein Effekt davon, ja. Wenn einmal dieser "Zustand" des ewigen Nachladens erreicht ist, zieht sich das durch alle Views durch. 
Ich muss den Fehler halt irgendwie reproduzieren können, um den zu analysieren und zu validieren, ob ein Bugfix den behebt. Mit den Schritten kann ich das.

**Comment by AkumaNoTsubasa** [comment]
![image](https://user-images.githubusercontent.com/627469/197386080-952582bd-1cd6-43fa-8bb8-1c2b435fb6fc.png)
Bin grad im pr0 in den PNs und da passiert es auch

Hier mal der Stuff der grad in der Konsole ist, falls das hilft. Das zensierte sind Usernamen. Wenn die File zum User eine Zeilenanzeige hatte war es immer Zeile 1

![image](https://user-images.githubusercontent.com/627469/197386190-d47ecbf0-c945-4075-b638-f5b4cc4f1284.png)
![image](https://user-images.githubusercontent.com/627469/197386205-0c12d04c-058a-476f-8aab-6f0e940821a3.png)
![image](https://user-images.githubusercontent.com/627469/197386231-a25adbae-695a-423c-88b2-ab3bbd13d9a9.png)
![image](https://user-images.githubusercontent.com/627469/197386261-1948c8c2-fd66-4d9e-8454-0c7e9cf787d0.png)
Hoffe das Hilft maybe

**Comment by twobiers** [comment]
In der aktuellen Dev-Version scheint der Fehler nicht mehr aufzutreten. Ich kann ihn nicht mehr mit den Schritten oben reproduzieren. 
Weil der Bug mMn. recht kritisch ist, release ich das direkt, lasse das Issue aber offen, weil ich mir nicht sicher bin ob das wirklich ein Fix ist. Wäre cool, wenn du Rückmeldung geben kannst, falls es dir nochmal auffallen sollte.

**Comment by AkumaNoTsubasa** [comment]
Ich habs grad mal versucht zu erzwingen, aber aktuell scheints gefixt. Ich beobachte es aber definitiv weiter. Super Arbeit!
