### ISSUE TITLE
Feature Request Bilder Downloadbutton

### ISSUE THREAD

**Issue by Art0sh** [Scarwolf/p0weruser#119]
## Allgemeine Informationen
**Browser:** Alle

**Version:** Alle

**Modul:** Pr0p0ll

## Beschreibung
Wäre es möglich einen Downloadbutton hinzuzufügen, der es ermöglicht das aktuelle Bild in der größtmögichen auflösung (Halt dass das Vollbild genommen wird, wenn vorhanden) herunterlädt, und dabei die z.b. top 10 gesetzten Tags als Bildtitel benutzt?

**Comment by twobiers** [comment]
Der liebe @arellak hat das in #124 gemacht. In der Dev-Version verfügbar, nächstes Release dann in der normalen version.
