### ISSUE TITLE
rep0st plugin shows same URL as rep0st

### ISSUE THREAD

**Issue by andrmoel** [Scarwolf/p0weruser#12]
1. Enable rep0st plugin from p0weruser
2. Open https://pr0gramm.com/new/3702287
3. Klick on "rep0st?"

Expected: Some rep0st pictures or none of them
Actual: Same upload is marked as rep0st

![Unbenannt-2](https://user-images.githubusercontent.com/35029021/75069211-04a51280-54f1-11ea-8e30-e7f2f1a0a733.jpg)

**Comment by Scarwolf** [comment]
Thanks for reporting. Fixed in the newest Beta Release.
