### ISSUE TITLE
Schon-gesehen Markierung funktioniert seit Update nicht mehr

### ISSUE THREAD

**Issue by egsAE** [Scarwolf/p0weruser#121]
## Bug Summary / Fehlerbeschreibung
Seit dem gestrigen Update funktioniert die "schon-gesehen" Funktion nicht mehr. Ein- und ausschalten in Tampermonkey bewirkt keine Änderung. 

## Steps to Reproduce the Problem / Wie kann der Fehler reproduziert werden

Pr0gramm öffnen, Post anklicken, es wird keine Markierung gesetzt.

## Specifications / Daten

  - Version: 2.5.0
  - Browser: Chrome Version 108.0.5359.125
  - Active p0weruser Modules: "Benis in Navigation", "Bereits-gesehen Markierung" (+"Eigene Favoriten ebenfalls..")

**Comment by twobiers** [comment]
Gibt es in der Entwicklerkonsole einen Fehler?

**Comment by egsAE** [comment]
Der Wechsel auf das Nutzerprofil und zurück bringt keine Änderung.
Hier die Konsole:

![image](https://user-images.githubusercontent.com/121388243/209479016-ec6f05b2-52f2-400e-9500-f26c0bd4c53b.png)

Habe gerade mal ein Inkognito Fenster geöffnet, Tampermonkey dort aktiviert und mich eingeloggt, dann funktioniert es wieder! Kann ich die Website-Daten irgendwie zurücksetzen, sodass die alten "schon gesehen" Markierungen erhalten bleiben?

**Comment by twobiers** [comment]
Perfekt, danke. Ich konnte den Fehler reproduzieren und habe ihn behoben, nach einem Update sollte alles passen.

P.S.: Die "Bereits gesehen" Markierungen können jetzt optional mit den pr0 servern synchronisiert werden (Siehe Einstellungen von p0weruser). Ansonsten findest du alle Daten im LocalStorage vom Browser, wenn du dir ein Backup machen möchtest.

**Comment by egsAE** [comment]
Perfekt, funktioniert wieder. Besten Dank!
