### ISSUE TITLE
Open in new Tab - Kommentare Spalte wird falsch und fehlerhaft angezeigt - WideScreen

### ISSUE THREAD

**Issue by oliver-koch** [Scarwolf/p0weruser#125]
## Bug Summary / Fehlerbeschreibung
Mit der neuen DEV Version 2.5.1-dev-1676447000397 wird im WideScreen Mode die Kommentarspalte rechts statt links angezeigt,
wenn das Bild/Video per "mittlerer Maustaste" oder "Open in new Tab" geöffnet wird.
Zusätzlich werden die Kommentar nicht geladen. Bei weiterschalten auf das nächste Bild gehts dann wieder.

## Steps to Reproduce the Problem / Wie kann der Fehler reproduziert werden

  1. Pr0gramm öffnen
  2. Bild per "mittlerer Maustaste" oder "Open in new Tab" in neuen Tab öffnen
  3. Bild wird links statt mittig angezeigt, Kommentarspalte ist rechts, keine Kommentare

## Specifications / Daten

  - Version: 2.5.1-dev-1676447000397
  - Browser: Firefox 109.0.1 (64-Bit)
  - Active p0weruser Modules:
    +Stilisierung Einzelne Styleanpassungen
    +Erweiterte Kommentare Erweitert die Kommentare um Farben und weitere Funktionen
    +Anonymous Title Entfernt den Top Tag aus dem Titel oder wähle einen eigenen Titel.
    +Desktop Notifications Informiert bei neuen Nachrichten
    +Texterkennung Extrahiere Text aus Bildern.
    +Rep0st Check Frage rene8888, ob es sich um einen rep0st handelt.
    +Repost Markierung Markiert Reposts in der Übersicht
    +Link to Statistics (Pr0mium) Verlinkt in der Navigation-Bar rechts oben auf die neue Statistik-Seite
    +"Bereits gesehen"-Markierung Markiert bereits gesehene Medien.
    +Widescreen Mode Stellt das pr0 im Breitbildmodus dar.

**Comment by twobiers** [comment]
Hängt zusammen mit dem Workaround in #122 denke ich. Ich überleg mir was.

**Comment by twobiers** [comment]
@oliver-koch Ich habe ein paar Änderungen gemacht, die das Problem für mich beheben. Bitte teste mal ob das für dich auch funktioniert.
