### ISSUE TITLE
Scrollen geht nicht mehr nach dem öffnen eines Hochlads

### ISSUE THREAD

**Issue by LoonyBeLuna** [Scarwolf/p0weruser#128]
## Checklist

- [X ] I am sure that the issue comes from p0weruser (verified by deactivating all other addons / private window) / Ich bin mir sicher, dass der Fehler durch p0weruser kommt (geprüft durch das deaktivieren anderer Addons / verwenden eines privaten Fensters).

Script deaktiviert, dann neugeladen, Adblocker ist aus (Alles für die Kohle).

## Bug Summary / Fehlerbeschreibung
Nach öffnen eines Hochlads und dann drücken von ESC friert das Bilderbrett ein, Scrollen geht nicht mehr.
Rechts/links klicken auf der Tastatur geht.
Scheint nicht zu passieren wenn ausgeloggt ¯\_(ツ)_/¯

## Steps to Reproduce the Problem / Wie kann der Fehler reproduziert werden

Pr0 benutzen und irgendwas anklicken, dann ESC drücken und dann geht scrollen nicht mehr.
Bin gerade nicht angemeldet und JETZT passiert der Bug nicht (habe aktuell 5 Tage bann weil ich Google witz gemacht habe...)

## Specifications / Daten

  - Version:  1.9.0
  - Browser: Firefox
  - Active p0weruser Modules: Keine Ahnung, weil gebannt :D Widescreen startseite, Kommentarketten (farbig), rotes Design.

**Comment by twobiers** [comment]
Sorry, Version 1.9.0 kann ich nicht supporten. In der aktuellen Version 2.6.0 ist das nicht reproduzierbar

**Comment by LoonyBeLuna** [comment]
> 

Ich denke ich war in 1.9. weil die neuste Version irgendein anderen Bug hatte, weswegen ich nicht die Version nutzte.
