### ISSUE TITLE
Schutz vor Autobann

### ISSUE THREAD

**Issue by andrmoel** [Scarwolf/p0weruser#13]
Gibt ja jetzt die Autobann Funktion auf dem pr0. Das p0weruser sollte die Kommentage bzw. Tags vor dem Absenden prüfen und so einen Autobann verhindern.

Autobann verhindern bei Kommentaren:
* Kommentare mit einem Zeichen

Autobann verhindern bei Tags:
* "Tag deinen Scheiß"

Gibt es noch mehr?

Kommentar von @RundesBalli

> Kommentare mit einem Zeichen sind - ohne das HTML zu manipulieren - am PC gar nicht mehr möglich, da das Textfeld auf pr0gramm eine Mindestlänge erfordert.
> `<textarea minlength="3" class="comment" name="comment" required="" placeholder="Kommentar schreiben…" title="Kommentar schreiben [c]"></textarea>`
> 
> Zu den verbotenen Tags könnte man @mopsalarm|s Funktion ggf nutzen:
> https://github.com/mopsalarm/Pr0/blob/4d44a96b4564f159f4911e08c08e7ff8149bd4c7/app/src/main/java/com/pr0gramm/app/ui/TagSuggestionService.kt#L31
> https://github.com/mopsalarm/Pr0/blob/4d44a96b4564f159f4911e08c08e7ff8149bd4c7/app/src/main/java/com/pr0gramm/app/ui/TagSuggestionService.kt#L52

**Comment by Scarwolf** [comment]
Wie @RundesBalli schon sagte ist das Problem mit den zu kurzen Kommentaren bereits auf pr0gramm selbst gelöst.

Zu den verbotenen Tags/Kommentaren: Wenn man ganz regulär kommentiert, dann passiert auch nichts. In Absprache mit @FlorianMaak und @RundesBalli werden wir keine Funktionen einbauen die einen Bann verhindern. Wir sind der Meinung dass jeder selbst dafür verantwortlich ist was er taggt/kommentiert.
