### ISSUE TITLE
Man muss 2x zurück drücken um bei Verlinkungen zurück zu kommen und kann nicht wieder vorwärts.

### ISSUE THREAD

**Issue by Nyunyun** [Scarwolf/p0weruser#130]
## Checklist

- [ X] Ich bin mir sicher, dass der Fehler durch p0weruser kommt, durch verwenden eines privaten Fensters.

## Bug Summary / Fehlerbeschreibung

Sobald eine Option aktiviert ist von p0weruser (egal ob Stilisierung, anonymer Titel, etc.), muss man 2x zurück drücken um von einer Verlinkungen zurück zu kommen. Möchte man wieder vorwärts, um sich vielleicht das Bild/Video genauer anzuschauen, dann geht das nicht und man muss neu auf die Verlinkung klicken.

## Steps to Reproduce the Problem / Wie kann der Fehler reproduziert werden

  1. Aktiviere irgendeine Option von p0weruser.
  2. Öffne ein Bild/Video in der ein Kommentar mit Verlinkung auf ein anderes Bild/Video existiert.
  3. Gehe zurück via Maustaste oder Browserelement.
  4. Gehe nochmal zurück, um wirklich zurück zu kommen.
  5. Versuche wieder vor zu gehen.

## Specifications / Daten

  - Version: 2.6 Stable, sowie Dev
  - Addon: Violentmonkey 2.14
  - Browser: Firefox 113.0.2 / 64-bit
  - OS: Windows 10 / 64-bit (wahrscheinlich irrelevant)
  - Active p0weruser Modules: Irrelevant, ist mit allen Einstellungen so.

**Comment by twobiers** [comment]
Mit https://github.com/Scarwolf/p0weruser/commit/146442046190937b057606e1840bf5868447bab1 konnte ich das Problem beheben. Ist in der Dev-Version jetzt drinnen. Bitte einmal testen, dann release ich das.

**Comment by Nyunyun** [comment]
Hab es getestet und es scheint problemlos zu funktionieren. Danke! :)

**Comment by Nyunyun** [comment]
Hab es getestet und es scheint problemlos zu funktionieren. Danke! :)
