### ISSUE TITLE
Webseite läd nichtmehr korrekt

### ISSUE THREAD

**Issue by Tangado-Haid** [Scarwolf/p0weruser#138]
## Checklist

- [X ] I am sure that the issue comes from p0weruser (verified by deactivating all other addons / private window) / Ich bin mir sicher, dass der Fehler durch p0weruser kommt (geprüft durch das deaktivieren anderer Addons / verwenden eines privaten Fensters).

## Bug Summary / Fehlerbeschreibung
Die Webseite läd nichtmehr richtig:
Ich klicke auf zb "neu" und der Ladebalken unter der Leiste kriecht sich zu Tode und kommt nicht zu einem Ende. Wenn ich dann einmal die URL markiere und Enter drücke läd er zwar sofort aber nur die "erste Seite" und keine Post darunter. Neu läd er zb nur von 5861361 bis 5861202 weiter nach rechts klicken funktioniert nicht. 
Die "Gesehen" Markierungen funktionieren auch nichtmehr.

## Steps to Reproduce the Problem / Wie kann der Fehler reproduziert werden

  1.Mit Aktiviertem Userscript das Pr0 aufrufen
  2. ¯\_(ツ)_/¯

## Specifications / Daten

  - Version: 2.8.0
  - Browser: Chrome Version 117.0.5938.92
  - Active p0weruser Modules: 1

**Comment by Tangado-Haid** [comment]
Vor 3 Tagen Spontan aufgetreten

**Comment by RundesBalli** [comment]
Kann ich bestätigen. Hab das Problem auch.

Wenn die Seiten nicht durchladen einfach im neuen Tab öffnen, dann gehts erstmal übergangsweise.

**Comment by Tangado-Haid** [comment]
mit 1.7.9 (aaaaaaltes Backup) geht seltsamer weise alles

**Comment by Tangado-Haid** [comment]
> Kann ich bestätigen. Hab das Problem auch.
> 
> Wenn die Seiten nicht durchladen einfach im neuen Tab öffnen, dann gehts erstmal übergangsweise.

Läd er bei dir neu auch erst wenn du 2 mal klickst?

**Comment by RundesBalli** [comment]
Nein, nur wenn ich /new so öffne wie beschrieben (neuer Tab) oder direkt.

**Comment by twobiers** [comment]
Kann bislang nur sagen, dass es an diesen Zeilen liegt. Weiß noch nicht was ich da machen kann ohne viel umzubauen.
https://github.com/Scarwolf/p0weruser/blob/142f9a369caacd1daccb8a59e106332dbe0a3c57/src/EventHandler.js#L22-L50

**Comment by RundesBalli** [comment]
> Sollte durch [7860157](https://github.com/Scarwolf/p0weruser/commit/78601576e8a318e7bcb045045022f0dfa8937034) behoben sein. Release jetzt eine neue Version.

funktioniert bei mir wieder einwandfrei, thy

**Comment by Tangado-Haid** [comment]
> Sollte durch [7860157](https://github.com/Scarwolf/p0weruser/commit/78601576e8a318e7bcb045045022f0dfa8937034) behoben sein. Release jetzt eine neue Version.

Danke für die schnelle und prompte Lösung
