### ISSUE TITLE
"Bereits gesehen" Speichergröße

### ISSUE THREAD

**Issue by RundesBalli** [Scarwolf/p0weruser#14]
Zusätzlich zu #7:

Wenn ich das richtig sehe speichert das "bereits gesehen" Modul nur 10.000 Einträge, was wirklich gar nicht viel ist. 
https://github.com/Scarwolf/p0weruser/blob/20916dd1bdd0b3ac1ce2e7625f18c04f7824fc06/src/module/ViewedPostsMarker.js#L52-L62

Wäre es machbar das auf 1.000.000 zu erhöhen? Oder einfach ohne Limit zu machen?

Ich meine mich zu erinnern, dass die Posts alle in **einem** "local storage Eintrag" gespeichert werden. Vielleicht müsste man das umbauen. Das ["sch0ngesehen" Addon](https://pr0gramm.com/new/3568968) macht das so, dass es "Chunks" abspeichert:
![grafik](https://user-images.githubusercontent.com/46271553/81493840-2ae27f00-92a4-11ea-9f50-a0f4b1287b24.png)

Da ich sehr viele Posts ansehe wäre das wirklich von Vorteil, wenn ALLE Posts korrekt markiert wären.

**Comment by tobi6112** [comment]
So wie ich das sehe dürfte da nichts gegen sprechen, allerdings wäre es wohl sinnvoll die derzeitige Implementierung was aufzupeppen, denn mit ein paar Millionen Einträgen könnten wir in Probleme geraten. Ich werde mich drum kümmern.

**Comment by RundesBalli** [comment]
Vergessen? PR gibts ja schon :-D

**Comment by twobiers** [comment]
> Vergessen? PR gibts ja schon :-D

Joa. Der alte PR war jetzt schon wieder zu alt, habe Teile der Implementierung in einem neuen PR zusammengefasst und erweitert. 
Möchte zwei Sachen noch fixen und dann nochmal in Ruhe drüber schauen, dann kann ich das in die Dev Version merge.

**Comment by twobiers** [comment]
Der PR #120 ist denke ich jetzt soweit, dass ich ihn mergen könnte, aber ich möchte gerne nochmal in Ruhe drüber schauen.
