### ISSUE TITLE
Pr0 lädt nicht vollständig

### ISSUE THREAD

**Issue by ByteRaper** [Scarwolf/p0weruser#140]
## Checklist

- [x] I am sure that the issue comes from p0weruser (verified by deactivating all other addons / private window) / Ich bin mir sicher, dass der Fehler durch p0weruser kommt (geprüft durch das deaktivieren anderer Addons / verwenden eines privaten Fensters).

## Bug Summary / Fehlerbeschreibung
Wenn man das Pr0 über folgende URL aufruft:
https://pr0gramm.com/new/!%20kadse%20|%20katze
lädt nach kurzem scrollen nichts mehr nach egal ob widescreen an oder aus.

## Steps to Reproduce the Problem / Wie kann der Fehler reproduziert werden

  1. https://pr0gramm.com/new/!%20kadse%20|%20katze
  2. scrollen.

## Specifications / Daten

  - Version: 2.8.1
  - Browser: Firefox
  - Active p0weruser Modules: Widescreen

**Comment by twobiers** [comment]
Hab's versucht mit 5949c9ff3c4260a34808c15b8dd5e8658d8d56bc zu fixen. Neue Version ist gleich da.
Ich hoffe, dass dadurch nichts anderes kaputt geht.

**Comment by twobiers** [comment]
FYI: Ich habe die Änderung rückgängig gemacht, weil was anderes kaputt gegangen ist. Sollte aber trotzdem jetzt weiterhin funktionieren. Meld dich kurz, falls das wieder auftreten sollte.
