### ISSUE TITLE
Gesehen Markierung mit aktivem Filter buggt

### ISSUE THREAD

**Issue by pr0lerama** [Scarwolf/p0weruser#141]
Wenn man einen Filter benutzt, werden die bereits gesehenen Posts markiert, welche währenddessen angesehen wurden. Reloadet man die Seite mit F5 verschwinden alle Markierungen von Gesehen wieder (Filter ist weiterhin angewendet).

## Specifications / Daten

  - Version: 2.8.2
  - Browser: Brave
  - Active p0weruser Modules:

Stilisierung

Erweiterte Kommentare
-Kommentarfarbe AN

Benis in Navigation
[WIP] Chat
Desktop Notifications
Texterkennung
Rep0st Check

"Bereits gesehen"-Markierung
-Lesend Synchronisieren

Nachrichten Schnellzugriff
Widescreen Mode
Download-Button

**Comment by twobiers** [comment]
Die "Bereits gesehen" markierungen werden periodisch gesichert. pr0gram synchronisiert sich regelmäßig mit den servern um bspw. den angezeigten Benis zu aktualisieren oder zu prüfen ob neue Nachrichten vorliegen. 
Wenn das geschieht, werden auch die "bereits gesehen" markierungen gespeichert. 
Das ist deshalb nötig, weil das speichern ziemlich rechenintensiv ist. Wenn man das bei jedem Post macht, wäre es sehr inperformant, daher will ich das nicht ändern.

Rechne damit, dass die gesehenen Posts ungefähr jede Minute gespeichert werden.

**Comment by twobiers** [comment]
Die Posts werden bereits lokal gespeichert, müssen aber komprimiert gespeichert werden (Siehe z.B. #14) und die entsprechende Verarbeitung kostet Rechenleistung. Deswegen will ich das auch nicht bei jedem Post machen.
Ich kann versuchen die Posts dann zu synchronisieren, wenn die Seite neu geladen wird bzw. die Seite verlassen wird. Aber groß etwas am Speicher umbauen möchte ich nicht mehr da das hoffentlich über kurz oder lang sowieso ein pr0gramm Feature wird.

Ist übrigens auch ein Duplikat zu #126.
