### ISSUE TITLE
Anzeigen wie viel Blussi bis beliebt

### ISSUE THREAD

**Issue by andrmoel** [Scarwolf/p0weruser#16]
Ich könnte mir eine Anzeige unter jedem Post vorstellen, die sagt, wie viele Blussis noch benötigt werden, um auf Beliebt zu kommen.

Beispiel:
![image](https://user-images.githubusercontent.com/35029021/82750249-0c55ab00-9daf-11ea-8da8-ff90532aadbe.png)

Formel: 
B=7,2857*M+16 (nachts 15 statt 16)
B = Anzahl Blussis für beliebt
M = Anzahl Minusser auf dem Post
Das in maximal 3 Stunden.

https://pr0gramm.com/new/3120130:comment29039586

**Comment by Scarwolf** [comment]
Danke an @Robinatus 

Closed - https://github.com/Scarwolf/p0weruser/pull/28
