### ISSUE TITLE
Untertitel / CC Symbol fehlt mit Widemode enabled

### ISSUE THREAD

**Issue by Davai0** [Scarwolf/p0weruser#163]
## Checklist

- [x] I am sure that the issue comes from p0weruser (verified by deactivating all other addons / private window) / Ich bin mir sicher, dass der Fehler durch p0weruser kommt (geprüft durch das deaktivieren anderer Addons / verwenden eines privaten Fensters).

## Bug Summary / Fehlerbeschreibung
Das Symbol für die Untertitel wird mir nicht angezeigt rechts unten im Video.

## Steps to Reproduce the Problem / Wie kann der Fehler reproduziert werden

  1. p0weruser mit Widemode enabled nutzen
  1. Untertitelsymbol fehlt
  1. Widemode ausmachen und sie werden wieder angezeigt

## Specifications / Daten

  - Version: 2.9.1
  - Browser: Chrome Version 119.0.6045.124 W10
  - Active p0weruser Modules: Widemode

**Comment by twobiers** [comment]
Danke, gefixt in df36dbe31c0625206a47c6fe6f9b5b24621ab0e3
