### ISSUE TITLE
Sammlungen hat Widescreen Mode zerstört

### ISSUE THREAD

**Issue by Scarjit** [Scarwolf/p0weruser#18]
## Allgemeine Informationen
**Browser:** Firefox

**Version:** 1.4.0

**Modul:** Widescreen Mode

## Fehlerbeschreibung

1. Benutzung von Pfeiltasten ist nicht mehr möglich zum Links/Rechts Navigieren.
2. Tag's werden nicht mehr angezeigt
3. Upload Zeit & User werden nicht angezeigt
4. Favo Button (bzw. der neue Sammlungen Pfeil) wird nicht angezeigt.
5. Es wird nur der erste Kommentar angezeigt
6. Videos werden nach wenigen Millisekunden an den rechten Bildschirmrand verschoben

Widescreen aktiviert:
![Widescreen](https://img.dynts.pro/8d4ac3c168)
Widescreen deaktiviert:
![Ohne Widescreen](https://img.dynts.pro/f7e707e8ea)

## Aktuelles Verhalten
> Siehe oben

## Erwartetes Verhalten
> Pfeiltasten sollten funktionieren
Tags, upload Zeit, User, Favo Button, Sammlungen Pfeil sollten angezeigt werden.

## Reproduzierbarkeit
> Widescreen modul laden

**Comment by Scarwolf** [comment]
Heyho. Danke für den Report. Ein Fix ist seit heute morgen draußen, es kann sein dass das Update erst später ausgeliefert wird weil unser CDN Provider das ziemlich lange Cacht.

Hier ist unsere neue Update Url, darüber kann ebenfalls die Version mit dem Fix (v1.4.1) installiert werden. https://scarwolf.github.io/p0weruser/p0weruser.user.js
