### ISSUE TITLE
up/down anzeige - option das es sofort sichtbar ist wieder möglich machen?

### ISSUE THREAD

**Issue by Xiller** [Scarwolf/p0weruser#19]
Halli Hallo,

die up/downs sind weg.
Dann rausgefunden: okay mit mouseover sieht man diese wieder.

Wäre es möglich dennoch die wieder standardmäßig anzuzeigen? [über eine Checkbox in den Optionen habe es nicht gefunden, hoffe war nicht 3x blind]

**Comment by Xiller** [comment]
Glaube ich muss mich korrigieren? Jedenfalls ist es wieder da.
Mir ist aber auch noch der Punkt aufgefallen, ich habe parallel Cust0mPr0gramm drauf, evtl. hat sich das nur untereinern gebissen mit p0weruser. Glaube man kann Closen, wenn ihr nix gemacht habt. Danke

**Comment by Scarwolf** [comment]
Jup, wir haben da nix daran gemacht. Mehrere Userscripte laufen zu haben ist meist Kontraproduktiv, vorallem da sich viele Features von p0weruser mit Cust0m Überschneiden.

Ich close dann mal.
