### ISSUE TITLE
Kompatibilität mit Violentmonkey

### ISSUE THREAD

**Issue by jkhsjdhjs** [Scarwolf/p0weruser#20]
Das Skript ist in der aktuellen Version nicht mit Violentmonkey kompatibel. Das liegt daran, dass in der ersten Zeile `// [pr0]  // ==UserScript==` statt `// ==UserScript==` steht. Das erlaubt Violentmonkey nicht [1]. Laut GreaseSpot, einem Wiki zum Skripten mit Greasemonkey, ist es ebenfalls nicht erlaubt [2].
Warum also steht `// [pr0]` in der ersten Zeile?

[1] https://violentmonkey.github.io/api/metadata-block/
[2] https://wiki.greasespot.net/Metadata_Block#Syntax

**Comment by Scarwolf** [comment]
Dank an einem neuen Webpack-Build Plugin fürs Userscripts steht jetzt nicht mehr `// [pr0]` in der ersten Zeile.

Danke an @Robinatus für die PR.
