### ISSUE TITLE
Download-Button

### ISSUE THREAD

**Issue by YoYoFreakCJ** [Scarwolf/p0weruser#209]
## Allgemeine Informationen
**Browser:** Alle

**Version:** Alle

## Beschreibung
pr0gramm.com hat einen Button zum Herunterladen des Posts. Speziell bei Videos hat dieser Button die Eigenschaft, das Video nicht im vp9-Format zum Download anzubieten, sondern ohne vp9, als "normales" mp4. Diese Information wurde mir vom pr0gramm-Team zugespielt. Diverse Software kann noch nicht mit dem vp9-Format arbeiten, weshalb ich diese Basisfunktionalität auch gerne im p0weruser sehen würde.

Hinweis: Per Rechtsklick auf das Video -> "Video speichern unter..." wird die vp9-Variante heruntergeladen, weshalb das keine Option ist.

Der Button:
![grafik](https://github.com/Scarwolf/p0weruser/assets/59722190/85f4db55-c7d8-48b5-a4d0-aaae7d3d65ca)

Der Link im Button:
![grafik](https://github.com/Scarwolf/p0weruser/assets/59722190/60e0a037-93c7-4834-8920-6fd08f43a7b7)
Wie zu sehen ist, ist in der URL nicht "-vp9" im Dateinamen enthalten.

Für den Download-Button kann aus dem API-Response aus `variants` der Eintrag mit `name`=`source` gewählt werden.

![grafik](https://github.com/Scarwolf/p0weruser/assets/59722190/b8affc24-6016-4220-a00c-ab839a33e27a)

Ein neuer Download-Button für das p0weruser-Script könnte z.B. neben dem Punkt neben dem Uploader-Namen sein (damit er nicht zu nahe am Melden-Button ist).

**Comment by twobiers** [comment]
Vertehe den request nicht. Willst du zwischen den verschiedenen Formaten wählen können? Der Mp4 download ist ja bereits der default.

**Comment by YoYoFreakCJ** [comment]
Nein, ich möchte generell einen Download-Button wenn p0weruser aktiv ist. Meine Wissens nach gibt es den Button gar nicht wenn p0weruser aktiv ist. Oder gibt es den bereits und ich sehe ihn nur nicht?
