### ISSUE TITLE
Eigene Posts koennen keiner Sammlung zugewiesen werden.

### ISSUE THREAD

**Issue by Xenira** [Scarwolf/p0weruser#21]
## Allgemeine Informationen
**Browser:** Chromium (Vivaldi)

**Version:** 1.4.1

**Modul:** 

## Fehlerbeschreibung
> Der Button zum Hinzufuegen oder Entfernen von posts aus einer Sammlung fehlt bei eigenen posts im widescreen modus.

## Aktuelles Verhalten
> Der Button wird bei eigenen Posts nicht angezeigt.

## Erwartetes Verhalten
> Der Button wird bei allen Posts angezeigt.

## Reproduzierbarkeit
> Einen eigenen Post oeffnen.

**Comment by Scarwolf** [comment]
Besten Dank.
