### ISSUE TITLE
User Script funktioniert nicht in Safari (Addon: Userscripts)

### ISSUE THREAD

**Issue by daranto** [Scarwolf/p0weruser#218]
## Checklist

- [ X] I am sure that the issue comes from p0weruser (verified by deactivating all other addons / private window) / Ich bin mir sicher, dass der Fehler durch p0weruser kommt (geprüft durch das deaktivieren anderer Addons / verwenden eines privaten Fensters).

## Bug Summary / Fehlerbeschreibung

Das Script wurde hinzugefügt (Stable & DEV) doch die Seite wird nicht verändert. Im Safari Console Log tauchen folgende Fehlermeldung auf: 

- p0weruser - Rel0aded [Dev].user.js @inject-into value set to 'content' due to @grant values: GM_info,GM_xmlhttpRequest 
- p0weruser - Rel0aded [Dev].user.js error: ReferenceError: Can't find variable: jQuery

## Steps to Reproduce the Problem / Wie kann der Fehler reproduziert werden

  1. Install Script in Safari
  2. Try to open pr0gramm.com
  
## Specifications / Daten

  - Version: Dev & Stable
  - Browser: Safari (MacOS)
  - Active p0weruser Modules: -

**Comment by grant** [comment]
Sorry man

**Comment by daranto** [comment]
Da man als Apple User ja bereit ist Geld in die Hand zu nehmen: 
https://apps.apple.com/us/app/tampermonkey/id1482490089

Mit der App läuft es ohne Probleme.
