### ISSUE TITLE
Seitenaufbau verzögert durch TLS-Handshake mit maxcdn.bootstrapcdn.com

### ISSUE THREAD

**Issue by chris-kwl** [Scarwolf/p0weruser#30]
## Allgemeine Informationen
**Browser:** Firefox 79.0

**Version:** 1.5.1 und älter

**Modul:** addStyles()

## Fehlerbeschreibung
> Für die Darstellung des Häkchens bei der Repost Markierung wird die awesome-Font von maxcdn.bootstrapcdn.com geladen. Der TLS-Handshake wird bei mir jedoch teils massiv in die Länge gezogen:
>```
>curl https://maxcdn.bootstrapcdn.com -v --trace-time -6
>14:08:33.828000 * Rebuilt URL to: https://maxcdn.bootstrapcdn.com/
>14:08:33.875000 *   Trying 2001:4de0:ac19::1:b:1b...
>14:08:33.875000 * TCP_NODELAY set
>14:08:33.906000 * Connected to maxcdn.bootstrapcdn.com (2001:4de0:ac19::1:b:1b) port 443 (#0)
>14:08:33.906000 * schannel: SSL/TLS connection with maxcdn.bootstrapcdn.com port 443 (step 1/3)
>14:08:33.906000 * schannel: checking server certificate revocation
>14:08:33.921000 * schannel: sending initial handshake data: sending 194 bytes...
>14:08:33.921000 * schannel: sent initial handshake data: sent 194 bytes
>14:08:33.921000 * schannel: SSL/TLS connection with maxcdn.bootstrapcdn.com port 443 (step 2/3)
>14:08:33.937000 * schannel: failed to receive handshake, need more data
>14:09:29.421000 * schannel: SSL/TLS connection with maxcdn.bootstrapcdn.com port 443 (step 2/3)
>...
>```
> Der Standard-Timeout in Firefox liegt bei 10s.
> Könnte zu https://github.com/MaxCDN/bootstrapcdn/issues/1061 passen.
>
> Anstelle von https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css könnte https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css verwendet werden. Funktioniert so bei mir bestens.
>Habe die URI jetzt erst einmal für mich manuell angepasst, wenn das Verhalten reproduzierbar ist bitte anpassen oder die Font-Abfrage am besten ganz ersetzen.

## Aktuelles Verhalten
> Der Seitenaufbau bzw. das laden von Bildern/Videos/Previews wird teils massiv verzögert

## Erwartetes Verhalten
> –

## Reproduzierbarkeit
> Eventuell DS-Lite Anschluss, IPv6 erzwingen

**Comment by Scarwolf** [comment]
Konnte ich reproduzieren. Ist mit der neuesten Version ersetzt worden, danke dir.
