### ISSUE TITLE
Nachrichten Schnellzugriff Popup leitet auf 404 Seite weiter

### ISSUE THREAD

**Issue by shawly** [Scarwolf/p0weruser#34]
## Allgemeine Informationen
**Browser:** Chrome

**Version:** 1.5.2

## Fehlerbeschreibung
Wenn man das Feature "Nachrichten Schnellzugriff" aktiviert hat und dann auf die Nachrichten klickt, geht zwar das Popup auf aber man landet trotzdem auf der 404 Seite.
![image](https://user-images.githubusercontent.com/6448794/105531842-35d22800-5cea-11eb-81ea-dc627a62344d.png)

## Aktuelles Verhalten
Wenn man das Feature "Nachrichten Schnellzugriff" aktiviert hat und dann auf die Nachrichten klickt, geht zwar das Popup auf aber man landet trotzdem auf der 404 Seite.

## Erwartetes Verhalten
Nicht auf einer 404 Seite landen sondern auf der aktuellen Seite bleiben.

## Reproduzierbarkeit
Feature "Nachrichten Schnellzugriff" aktivieren. Auf Nachrichten Icon klicken.

**Comment by Scarwolf** [comment]
Danke fürs Melden. Hotfix 1.5.3 wurde deployt und sollte gleich verfügbar sein.
