### ISSUE TITLE
"Erweiterte Kommentarfunktion" blendet "Kommentar schreiben [c]" Tooltip über den eigentlichen Abschicken & Abbrechen Buttons ein

### ISSUE THREAD

**Issue by shawly** [Scarwolf/p0weruser#35]
## Allgemeine Informationen
**Browser:** Chrome

**Version:** 1.5.3

**Modul:** Erweiterte Kommentarfunktion

## Fehlerbeschreibung
"Erweiterte Kommentarfunktion" blendet "Kommentar schreiben [c]" Box über den eigentlichen Abschicken & Abbrechen Buttons ein, wenn man auf einen Kommentar antworten will. Das passiert nur beim Antworten auf einen Kommentar, nicht wenn man einen Kommentar direkt unter einem Post erstellen will.
![image](https://user-images.githubusercontent.com/6448794/105982369-78538600-6097-11eb-9748-5f96bd7b2634.png)

## Aktuelles Verhalten
Wie im Bild zu sehen wird eine graue Box über den eigentlichen Buttons eingeblendet die verschwindet, sobald der Mauszeiger nicht mehr über dem Text Input Feld ist.
Scheint ein Tooltip zu sein, der beim :hover auf die textarea getriggered wird:
![image](https://user-images.githubusercontent.com/6448794/105982607-c8cae380-6097-11eb-8394-a4a7d8524fd4.png)

## Erwartetes Verhalten
Kein Tooltip da dieser etwas redundant erscheint, alternativ an einer anderen Stelle einblenden.
![image](https://user-images.githubusercontent.com/6448794/105983005-5e667300-6098-11eb-9425-d0cf0e4830eb.png)

## Reproduzierbarkeit

1. "Erweiterte Kommentarfunktion" aktivieren.  
2. Irgendeinen Post mit Kommentaren öffnen.  
3. Auf "antworten" bei einem Kommentar klicken.  
4. Über die Textbox mit dem Mauszeiger hovern.

**Comment by tobi6112** [comment]
Ich kann den Bug nicht reproduzieren, ist der noch akut?

**Comment by Scarwolf** [comment]
Ebenfalls nicht reproduzierbar, hab ich früher schonmal getestet. Falls doch, bitte mehr Infos.

**Comment by shawly** [comment]
Ist immer noch reproduzierbar bei mir, bin auf Version 1.7.5, hab alle sonstigen Userscripts deaktiviert, hab alle Features bis auf Erweiterte Kommentarfunktion deaktiviert und es kommt immer noch.

**Comment by tobi6112** [comment]
> Ist immer noch reproduzierbar bei mir, bin auf Version 1.7.5, hab alle sonstigen Userscripts deaktiviert, hab alle Features bis auf Erweiterte Kommentarfunktion deaktiviert und es kommt immer noch.

Ich habe diesen "Kommentar schreiben [c]" Button noch nie gesehen. Weder in p0weruser oder auf pr0 selbst. Bist du dir sicher, dass du alle Userscripts deaktiviert hast?

**Comment by shawly** [comment]
Ja.

**Comment by shawly** [comment]
Das Styling dafür kommt auf jeden Fall hier her https://github.com/Scarwolf/p0weruser/blob/934d563411b0801a071f395c87a9eb562a2d2e10/src/style/advancedComments.less#L97

**Comment by shawly** [comment]
Jop es war der Aufruf in Zeile 43 hier: https://github.com/Scarwolf/p0weruser/blob/623e082e8df41387dc48cbc7a6d207576b564c47/src/module/AdvancedComments.js#L43

Hab ihn mal kurz rausgeworfen bei mir und jetzt taucht der Tooltip nicht mehr auf.

**Comment by shawly** [comment]
Wo Merge?
