### ISSUE TITLE
"Bereits gesehen"-Markierung

### ISSUE THREAD

**Issue by Michl7** [Scarwolf/p0weruser#36]
## Allgemeine Informationen
**Browser:** Chrome

**Version:** 1.6.0

**Modul:** "Bereits gesehen"-Markierung

## Fehlerbeschreibung
> Es werden keine Posts mehr als bereits gesehen markiert.

**Comment by Scarwolf** [comment]
Bist du pr0mium User? Kannst du mal manuell updaten und mir sagen ob es jetzt geht?
https://scarwolf.github.io/p0weruser/p0weruser.user.js

**Comment by Michl7** [comment]
Jop bin pr0mium user. 
Update hat es behoben! Top <3

**Comment by Scarwolf** [comment]
Top, danke für die Rückmeldung :)
