### ISSUE TITLE
URL not updating

### ISSUE THREAD

**Issue by FlorianMaak** [Scarwolf/p0weruser#37]
## Allgemeine Informationen
**Browser:** Chrome

**Version:** 1.6.0

**Modul:** Widescreen Mode

## Fehlerbeschreibung
> URL Updated sich nicht in der Adresszeile, wenn man den Post wechselt.

## Aktuelles Verhalten
> URL updated sich nicht.

## Erwartetes Verhalten
> URL soll aktuelle PostID enthalten

## Reproduzierbarkeit
> Post wechseln.

**Comment by Scarwolf** [comment]
Fixed
