### ISSUE TITLE
rep0st checker is broken

### ISSUE THREAD

**Issue by andrmoel** [Scarwolf/p0weruser#40]
Rene hat seinen Rep0st checker geupdated: https://rep0st.rene8888.at/

Damit funktioniert das Rep0st Feature im User-Script leider nicht mehr.

**Comment by Scarwolf** [comment]
Danke fürs melden.

Jeden Moment ist Version v1.7.0 verfügbar, der rep0st Checker wurde gefixt.
Ausserdem habe ich die Anzeige der von rep0st zurückgegebenen Probability integriert. 
Wird oben rechts bei jedem Ergebnis angezeigt.

**Comment by andrmoel** [comment]
Danke fürs schnelle fixen!

**Comment by andrmoel** [comment]
Würde das issue gerne noch mal öffnen lassen. Ich sehe jetzt leider immer nur ein einziges Bild als Repost-Vorschläge.
Die Liste, die vorher vorhanden war, ist defintiv hilfreicher.

**Comment by Scarwolf** [comment]
Hm, du hast recht, Tritt aber nicht bei jedem Bild auf. Ich werd mir das nochmal ansehen.

**Comment by Scarwolf** [comment]
v1.7.2 released.
