### ISSUE TITLE
Keine Kommentarspalte im Widescreenmodus

### ISSUE THREAD

**Issue by HamburgerTrunkenbold** [Scarwolf/p0weruser#57]
## Allgemeine Informationen
**Browser:** Chrome|Firefox

**Version:** Aktuell

**Modul:** Scripteigener Widescreen Modus

## Fehlerbeschreibung
Sobald der Widescreen Modus in den EInstellungen aktiviert wird, wird seit heute Nachmittag (Fr. den 06.08.21) die Kommentarspalte auf der linken Seite nicht mehr angezeigt. Adblocker etc. alles deaktiviert, Script neu installiert, keine Veränderung.

<img width="1434" alt="Bildschirmfoto 2021-08-06 um 17 29 01" src="https://user-images.githubusercontent.com/88550505/128534667-5177375d-bb38-4c64-a753-f090ad0fb1f3.png">

## Reproduzierbarkeit
Reproduziert auf Chrome, Brave und Firefox

**Comment by w00kee** [comment]
Selbes Problem Brave Browser aktuellste Version. Werbe Blocker abgestellt und auch den Brave internen Blocker abgestellt-> keine Besserung. Hoffe ihr findet nen fix Danke für eure Arbeit profitiere tag täglich davon :)

**Comment by Frubi22** [comment]
Grund ist das Update : 
KOMMENTARSORTIERUNG
6. Aug 2021 - 17:40
Kommentare des OPs werden priorisiert nach oben einsortiert. Das Verhalten ist somit der Android-App angepasst.
Kommentare mit Minusbenis, werden wie gewohnt nach dem Bewertungsverhalten sortiert.

**Comment by Scarwolf** [comment]
Danke fürs Melden, ich hab soeben Version 1.7.6 released die das Problem löst.

Update wie immer automatisch oder direkt über den Link: https://scarwolf.github.io/p0weruser/p0weruser.user.js
