### ISSUE TITLE
Content gestreckt

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [Scarwolf/p0weruser#59]
Aktuell wird der geöffnete Content beim Scrollen stark verzerrt.
![image](https://user-images.githubusercontent.com/627469/134668751-869da01e-37f8-40df-adee-f968dbd1b54c.png)

Auch ein Verhalten dass seit einiger Zeit auftritt: Wenn man ein Bild vergrößert über 
![image](https://user-images.githubusercontent.com/627469/134668846-d3d3ab3b-2d37-49e5-82f4-a1e27cc0d15d.png)
und das Bild schliesst, kann man erst im Content wieder scrollen, wenn man ein großes Bild über das Symbol vergrößert und wieder verkleinert, da das Script den Zustand der "Vergrößerung" speichert.

**Comment by Bara91** [comment]
Jap ist bei mir auch seit Gestern. Gibt es ein Workaround oder kommt ein fix? Danke.

**Comment by tobi6112** [comment]
@AkumaNoTsubasa @Bara91 Welchen Browser nutzt ihr und welche p0weruser Module habt ihr aktiviert? Kann das Problem mit dem Strecken nicht mit FF/Chrome reproduzieren.

Zweites Problem dürfte Duplikat zu #2 sein.

**Comment by tobi6112** [comment]
Nvm, ist bei bspw. folgendem Post der Fall: https://pr0gramm.com/top/4777212

**Comment by Bara91** [comment]
Brave Version 1.30.86 Chromium: 94.0.4606.61 (Official Build) (64-bit) Ich hoffe auf dem Bild ist alles was du brauchst. 

![2021-09-30 14_15_20-Window](https://user-images.githubusercontent.com/50118114/135453328-77782a1c-7daf-457a-8e56-8880bc275be4.png)

**Comment by Scarwolf** [comment]
Sollte gefixt sein, danke an @tobi6112

**Comment by AkumaNoTsubasa** [comment]
Ja, funktioniert wieder. Danke!
