### ISSUE TITLE
Repost checker Style defekt

### ISSUE THREAD

**Issue by andrmoel** [Scarwolf/p0weruser#61]
Nach dem neusten Update ist der Style des Repost Checker leider kaputt.

Screenshot: https://ibb.co/fF5gG9t

Ich denke das hier ist der Grund: https://github.com/Scarwolf/p0weruser/commit/970c6ec7ab38a9fe752db38e7f89d6f3aaae8848

**Comment by tobi6112** [comment]
Auch hier vermutlich Regression zu dem Fix in #59. Ich guck mir das nochmal genauer an
