### ISSUE TITLE
Anzeigeprobleme mit übergroßen Videos

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [Scarwolf/p0weruser#62]
![image](https://user-images.githubusercontent.com/627469/135631275-65909035-cc69-4ad1-bad1-5e52bc8b48dc.png)

Wird nicht mehr kleinskaliert.

**Comment by tobi6112** [comment]
Vermutlich Regression zu dem fix in #59 

Müssten uns den Style mal genauer anschauen...
