### ISSUE TITLE
Erweiterung des "Bereits gesehen"-Moduls

### ISSUE THREAD

**Issue by RundesBalli** [Scarwolf/p0weruser#7]
Relatiert: https://github.com/FlorianMaak/p0weruser/issues/86

## Allgemeine Informationen
**Modul:** "Bereits gesehen"-Markierung

Es wäre klasse, wenn die Daten, die aus dem Sync-Log kommen, ebenfalls als gesehen markiert werden würden.
Beispiel:
Man voted am Handy einen Upload, dann ist er ja gesehen worden. Demzufolge sollte es auch am PC als "gesehen" markiert werden.

Eventuell wird die Funktion aus @Mopsalarm s App dazu hilfreich sein:
https://github.com/mopsalarm/Pr0/blob/master/app/src/main/java/com/pr0gramm/app/services/VoteService.kt#L105

Vielleicht kann man ja auch die synchronisierten Posts aus Mopsalarms Datensatz dazu verwenden. Ich weiß allerdings nicht wo und wie die gespeichert werden. Es gibt aber in der Config der App einen Menüpunkt `Einstellungen` -> `Privatsphäre`:
![grafik](https://user-images.githubusercontent.com/46271553/57988735-edcd1d80-7a91-11e9-9228-e302faf3b2f2.png)
Vielleicht kann man ja darauf zugreifen und diese Daten ebenfalls in das "gesehen" Modul implementieren.

**Comment by mopsalarm** [comment]
Schaue mal nach dem KVService in der App. Gibt aber keine Garantie, dass der immer so läuft.

**Comment by RundesBalli** [comment]
Ich verlinke mal:

https://github.com/mopsalarm/Pr0/blob/master/app/src/main/java/com/pr0gramm/app/services/KVService.kt

**Comment by Scarwolf** [comment]
Der gute @tobi6112 hat das mal Probiert und fast komplett umgesetzt. Nach Absprache mit Syntax können wir das leider nicht machen.
