### ISSUE TITLE
Portieren von holzmaster's Augenzuckerl Blur

### ISSUE THREAD

**Issue by kavejra** [Scarwolf/p0weruser#80]
Portieren von holzmaster's [Augenzuckerl](https://github.com/holzmaster/augenzuckerl) Blur in p0weruser, mit der Moeglichkeit in den Einstellungen auf das native Design des Pr0s zurueck zu kehren.

**Comment by twobiers** [comment]
Ist in die Dev-Version unter eingbaut. Hier geht's zur Dev Version: https://scarwolf.github.io/p0weruser/p0weruser.dev.user.js
Gibt jetzt ein neues Modul "Stilisierung" unter dem du das aktivieren kannst.
Weiß noch nicht ob das so ne gute Lösung ist ein einzelnes Modul für kleinere Style-Adjustments zu machen, deshalb halt ich das release erstmal noch zurück.
