### ISSUE TITLE
Thumbnails not shown / loaded

### ISSUE THREAD

**Issue by Lightningblade** [Scarwolf/p0weruser#81]
## Allgemeine Informationen
**Browser:** Firefox

**Version:**1.8.2

## Fehlerbeschreibung
> https://pr0gramm.com/new/5116427:comment56749686

## Aktuelles Verhalten
> Keine thumbnails

## Erwartetes Verhalten
> Thumbnails

## Reproduzierbarkeit
> addon installieren -> pr0gramm.com öffnen

**Comment by arnili** [comment]
Can confirm.

**Comment by RundesBalli** [comment]
Kann ich bestätigen.

**Comment by NullDev** [comment]
Wurde uns auch bereits von mehreren Usern gemeldet

**Comment by RundesBalli** [comment]
Liegt am "Filter Markierungen"-Modul, habs grad im Ausschlussverfahren probiert.

**Comment by Lightningblade** [comment]
> Can confirm.

> Kann ich bestätigen.

Benutzt reactions ihr Lümmel. Will nur emails bei updates

**Comment by RundesBalli** [comment]
> > Can confirm.
> 
> > Kann ich bestätigen.
> 
> Benutzt reactions ihr Lümmel. Will nur emails bei updates

![grafik](https://user-images.githubusercontent.com/46271553/164314613-36fd6bd8-c04a-4857-9c31-870b37593897.png)

**Comment by RundesBalli** [comment]
Ich habe festgestellt, dass das pr0 seit heute die Thumbnails "smooth" / "fade-in" mäßig lädt. Das wird damit zusammenhängen, dass die Filtermarkierungen mit der neuen Funktion nicht klar kommen und sich da was beißt.

**Comment by Lightningblade** [comment]
Updates != closed.

> Liegt am "Filter Markierungen"-Modul, habs grad im Ausschlussverfahren probiert.

Ist doch super relevant.

**Comment by twobiers** [comment]
> Ich habe festgestellt, dass das pr0 seit heute die Thumbnails "smooth" / "fade-in" mäßig lädt. Das wird damit zusammenhängen, dass die Filtermarkierungen mit der neuen Funktion nicht klar kommen und sich da was beißt.

So ist es. Gefixt in 92b228deaf50cc52b5084d4ad5d5987d493e8a73

**Comment by RundesBalli** [comment]
Getestet, funktioniert.

Danke @twobiers
