### ISSUE TITLE
Steuerungen des Video Speed Controller Addon über den gesamten Stream verteilt

### ISSUE THREAD

**Issue by asd1234hf7** [Scarwolf/p0weruser#84]
Seit dem gestrigen update erscheint das Overlay vom Video Speed Controller Addon mehrfach über die gesamte Seite. Normalerweise soll es nur ein mal, oben links vom Video erscheinen.
Das kommt womöglich von den Kacheln im Hintergrund. Vielleicht denkt das Addon, das bei jeder Kachel ein Video abgespielt wird?

![grafik](https://user-images.githubusercontent.com/109418519/179353269-c2bea664-f15c-471f-b5e9-e4110a67ed2e.png)

Als Browser verwende ich Firefox

**Comment by twobiers** [comment]
Hi,

der Fehler kommt nicht durch p0weruser, sondern durch das neueste pr0gramm Update. pr0gramm hat jetzt Previews, wenn du über ein Video hoverst. Das wird deshalb von deinem Addon erkannt. P0weruser wurde mit dem letzten Update nur so angepasst, dass das unterstützt wird. 
Ich denke, ich kann da nichts machen, aber ich kann den Fehler mal weiterleiten.

**Comment by holzmaster** [comment]
Welches Addon verwendest du? Dann können wir das vielleicht bei pr0gramm selbst fixen.

**Comment by asd1234hf7** [comment]
Hi, danke für eure Rückmeldungen. Das Addon heißt "Video Speed Controller". Gibts auch für chrome

**Comment by holzmaster** [comment]
Ich hab Mal hier geschaut:
https://github.com/codebicycle/videospeed/blob/da0eaad79ef125bf3a4e70da392cdd9b14f49f5c/inject.js#L648

Das schaut auf das Aria-Tag. Vielleicht hilft das, wenn wir das bei pr0gramm hinzufügen. Ich kann das nachher machen. Magst du dich dann hier melden, ob es das fixt?

**Comment by twobiers** [comment]
Kannst es über folgenden Style fixen, dafür bräuchtest du aber wieder ein neues Addon was Custom CSS/UserCSS unterstützt. Ich habe drüber nachgedacht und kann es theoretisch auch in p0weruser einbauen. Das Problem ist nur, dass ich gerade noch nicht releasen kann, weil ein recht nerviger Bug existiert.
Ich mach mir darüber nochmal Gedanken ob es sinvoll ist das einzubauen.

```css
:not(.item-image)>.vsc-controller {
  display: none;
}
```

![image](https://user-images.githubusercontent.com/22715034/179359791-bdf7423c-f908-478b-919c-dbc81b792819.png)

**Comment by holzmaster** [comment]
Wir haben das mit dem aria-tag jetzt auf der Hauptseite und bei dem Addon.
Das aria-tag hinzuzufügen war schon eine gute Sache. Aber gefixt hat es das wohl nicht.

@asd1234hf7 wenn du magst, kannst du in den [Issues bei des Addons](https://github.com/codebicycle/videospeed/issues) nach einer Lösung schauen. Wenn du eine findest und sie kein Hack ist, würde ich das einbauen.
Ansonsten bleibt noch der CSS-Hack von oben.

**Comment by twobiers** [comment]
@asd1234hf7 Dieses neue UserScript würde dein Problem auch lösen.
```js
// ==UserScript==
// @name        VideoSpeedController Fix
// @description Style fix for VideoSpeedController Addon
// @version     1.0.0
// @include       /^https?://pr0gramm.com/.*$/
// @connect     pr0gramm.com
// ==/UserScript==



(function() {
    const style = document.createElement('style');
    style.type = 'text/css';
    style.innerText = ":not(.item-image)>.vsc-controller { display: none; }";
    document.head.appendChild(style)
})()
```

**Comment by asd1234hf7** [comment]
Vielen Dank euch beiden! Das mit dem UserScript hat das Problem behoben.
