### ISSUE TITLE
Timestamp im Notification Center zu lang

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [Scarwolf/p0weruser#88]
![image](https://user-images.githubusercontent.com/627469/179627192-af68422b-c7e7-4668-aa87-e4d9b1866ecb.png)

**Comment by twobiers** [comment]
Für mich micht reproduzierba - Mehr Details bitte. Der Tooltip wird nicht verändert, du scheinst noch weitere UserScripts installiert zu haben vermutlich kommt das daher.

**Comment by AkumaNoTsubasa** [comment]
Nope. Ist das einzige Userscript das ich nutze.
Was für Details brauchst du ? Ist erst seit dem aktuellen Update des Scripts. War vorher nie so.

**Comment by twobiers** [comment]
> Nope. Ist das einzige Userscript das ich nutze. Was für Details brauchst du ? Ist erst seit dem aktuellen Update des Scripts. War vorher nie so.

Wo genau tritt der Fehler auf? Ich brauche irgendwelche Ansätze um den zu reproduzieren. In welcher View bist du, welchen Browser nutzt du wo hoverst du drüber?

**Comment by AkumaNoTsubasa** [comment]
Aktueller Chrome. Im Message Dropdown. Passiert auch nur da. Ohne Userscript gibts das Message Dropdown Menü nicht, daher kann ich es ohne nicht testen. Nutze das Widescreen
