### ISSUE TITLE
Konfigurierbarkeit der Smooth Scrollbar

### ISSUE THREAD

**Issue by Flummi** [Scarwolf/p0weruser#89]
Wäre schön, wenn smooth-scrollbar via Settings togglebar wäre. Diese Verzögerung ist unfassbar nervig.

**Comment by twobiers** [comment]
Betroffener Browser, Beispiel wo es Auftritt und Fehlerbeschreibung würde helfen.

**Comment by twobiers** [comment]
Habe die Einstellungen ein bisschen angepasst, in der aktuellen Dev-Version ist das jetzt etwas unsmoother. 

Bitte probier das doch mal aus und gib Feedback ob das so okay ist: https://github.com/Scarwolf/p0weruser#installation
An der entsprechenden Konfigurierbarkeit werde ich bei Zeiten arbeiten, find ich gut.

**Comment by Flummi** [comment]
Entschuldige dass ich heute morgen so harsch war. Ich war ein wenig genervt. :D
In der Dev-Version fühlt es sich nun besser an.

Wie du schon richtig geraten hast: Scrollverhalten Kommentarsektion

Ausgefüllt hatte ich den Fragebogen nicht, da es eigentlich kein Bug ist und es nicht am Browser lag.

**Comment by twobiers** [comment]
Danke für die Rückmeldung, ich release im Laufe des Tages eine neue Version.

**Comment by twobiers** [comment]
Die Smooth Scrollbar wird mit dem nächsten Release entfernt, weil sie zu viele Probleme macht, stattdessen wird eine die native Scrollbar des Browsers genutzt.
