### ISSUE TITLE
Benisanzeige

### ISSUE THREAD

**Issue by RundesBalli** [Scarwolf/p0weruser#9]
Relatiert: https://github.com/FlorianMaak/p0weruser/issues/80

Weitergeleitet von https://pr0gramm.com/user/Nezos da er keinen Github Account hat:
Es wäre schön, wenn man auswählen könnte, dass der Username neben dem Benis angezeigt wird. Am liebsten Links davon.

Als kleine Ergänzung:
in /api/user/sync wird inzwischen der Score mit angezeigt. Den könnte man im selben Event wie die ungelesene-PNs Abfrage mit abfragen.

**Comment by Scarwolf** [comment]
https://github.com/Scarwolf/p0weruser/releases/tag/v1.4.0

**Comment by RundesBalli** [comment]
Getestet. Funktioniert.
