### ISSUE TITLE
Nachrichtenliste im Dropdown (Schnellübersicht) nicht sofort entfernen

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [Scarwolf/p0weruser#91]
Hallo,

seit dem neuen Update wird die Schnellübersicht beim Schließen sofort gelöscht. Das war sonst nie der Fall. Es wäre klasse, wenn man das Leeren der Übersicht deaktivieren könnte und stattdessen eine Option hätte zu sagen, dass man nur die X neuesten Benachrichtigungen sehen möchte.

Auch springt man nicht mehr zum entsprechenden Kommentar, wenn man darüber navigiert.

**Comment by twobiers** [comment]
> seit dem neuen Update wird die Schnellübersicht beim Schließen sofort gelöscht. Das war sonst nie der Fall.
Ich sehe auf Anhieb nicht, welche Änderung das verursachen sollte. Der lesen/ungelesen Status kommt von der pr0 API und wird durch p0wersuer nicht beeinflusst. 
Ich kriege auch nicht genug Nachrichten um das genauer beurteilen zu können, wie es vorher war. Würde es dir helfen eine Option einzuführen, die auch gelesene Nachrichten anzeigt aber nur ungelesene hervorhebt?

> Auch springt man nicht mehr zum entsprechenden Kommentar, wenn man darüber navigiert.
Danke für den Hinweis, da gab es noch eine notwendige Änderung. Bin gerade dran und der Fix dafür kommt dann im Laufe des Tages.

Danke für die Bugreports, bitte melde dich, sollte dir noch mehr auffallen, es hat mit dem Versionssprung auf 2.0.0 ein paar invasive Änderungen gegeben.

**Comment by AkumaNoTsubasa** [comment]
> Würde es dir helfen eine Option einzuführen, die auch gelesene Nachrichten anzeigt aber nur ungelesene hervorhebt?
Das wäre perfekt. Ist halt kacke, wenn du 10 neue Benachrichtigungen zu 5 Posts hast, einen anklickst und dann alles weg ist.
