### ISSUE TITLE
Nachrichtenleiste verschwindet

### ISSUE THREAD

**Issue by rottenpuppy** [Scarwolf/p0weruser#92]
## Allgemeine Informationen
**Browser:** Firefox

**Version:** 2.0.0

## Fehlerbeschreibung
> Die Informationsleiste ist falsch skaliert und geht über den Bildschirmrand hinaus, ferner ist die Formatierung zerschossen. 

## Erwartetes Verhalten
> Normalerweise sollte die Informationsleiste schön säuberlich aneinandergereiht sein, ohne den Bildschirm zu verlassen oder die Icons zu verschieben.

## Reproduzierbarkeit
> Er kann unendlich hervorgerufen werden, vermutlich ist die Aktualisierung des Skripts verantwortlich, wenn du Seite zu früh/zu spät lädt.
![p0weruser](https://user-images.githubusercontent.com/52719087/179730688-4da8dddb-fd02-4379-a20c-5d9a7fd9dd43.png)

**Comment by twobiers** [comment]
Danke. Kommt durch das "pr0poll" Modul, wenn es dich nervt kannst du das vorläufig deaktivieren. 
Ich hoffe, dass ich heute abend eine neue Version releasen kann, wo der Fehler weg ist.

**Comment by rottenpuppy** [comment]
Hey, danke für die schnelle Antwort. Stimmt, ohne pr0p0ll sieht alles super aus. Ich lasse das erstmal deaktiviert, mach dir (wegen mir) keinen Stress, geht ja auch ohne pr0p0ll Integration. 

Beste Grüße

**Comment by twobiers** [comment]
Ist schon fertig, alles gut. Das Update gestern war ziemlich invasiv und hat recht viele Fehler hervorgerufen, deshalb will ich das gebündelt releasen. Wenn alles gut geht, wie gesagt heute abend.

**Comment by rottenpuppy** [comment]
Moin, funktioniert einwandfrei. Vielen lieben Dank :)

Am Di., 19. Juli 2022 um 17:23 Uhr schrieb Tobi ***@***.***>:
