### ISSUE TITLE
Neue Kommentare erst nach Refresh sichtbar / Chache problem?

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [Scarwolf/p0weruser#98]
Seit gestern werden neue Nachrichten im Dropdown nur angezeigt, wenn man Refreshed und wenn man den Post schon mal offen hatte, wird man in einer gecachten Version des Posts geleitet in der das Kommentar noch nicht existierte.

**Comment by twobiers** [comment]
> Seit gestern werden neue Nachrichten im Dropdown nur angezeigt, wenn man Refreshed
Das sollte eigentlich nicht so sein. Jedes mal wenn du das Dropdown öffnest werden die Nachrichten neu geladen. Welchen Browser nutzt du?

> wenn man den Post schon mal offen hatte, wird man in einer gecachten Version des Posts geleitet in der das Kommentar noch nicht existierte
Ich befürchte, das wird nicht so einfach zu beheben sein - ich verstehe die Problematik aber da muss ich was tiefer graben. Schau ich mir am Wochenende mal genauer an.

In Version 1.x wurdest du vom Notification Center über Hardlinks weitergeleitet, jetzt eben über den pr0 internen router. Der macht das ganze flüssiger und den Vorteil würde ich ungerne ungerne verlieren.

**Comment by twobiers** [comment]
Halte ich nicht für sinnvoll das optional zu machen - selbst temporär, das sollte schon ordentlich gefixt werden. Wenn es dich hart nervt, kannst du über diesen Link auf v1.9.0 zurück.
https://github.com/Scarwolf/p0weruser/raw/f6e1cb5d07e5cb532e11b7b03c06d6f8ea4a7ee2/p0weruser.user.js

**Comment by AkumaNoTsubasa** [comment]
Nervt leider sehr hart, weil ich jetzt nur um die neuen Kommentare in der Benachrichtungsbox neu laden muss und dann noch mal den Post, wenn ich ihn schon gesehen hab. Das fuckt übel ab :/

**Comment by twobiers** [comment]
Ich kann das Problem mit einer "weichen" Navigation leider nur für den Widescreen Mode fixen, was nicht Sinn der Sache ist. 
Habe jetzt also eine "harte" Navigation eingebaut, die erzwingt ein neues rendering der View. Das sollte das Problem beheben.
Habe deine Nachricht zuerst auch falsch gelesen, ich dachte es werden auch neue Kommentare **im Dropdown** nicht angezeigt.

Vielleicht ist #94 dadurch jetzt auch Geschichte, wenn das der Fall ist, release ich die neue Version.

**Comment by AkumaNoTsubasa** [comment]
> Habe deine Nachricht zuerst auch falsch gelesen, ich dachte es werden auch neue Kommentare im Dropdown nicht angezeigt.

Schon richtig. Der Umschlag färbt sich und zeigt halt X an. Ich klicke drauf: Sehe nur die mir schon bekannten Kommentare (Nachrichten kein Plan, mir schreibt keiner). Ich drücke also F5 und darf die neuen Kommentare sehen. Dann klicke ich eines der Kommentare und der Post ploppt auf in gecachter Version.

**Comment by twobiers** [comment]
Okay dann doch. Wie gesagt, wird bei jedem öffnen des Dropdowns Alles über die pr0-interne API geladen. Das kannst du über den Network-Tab in deinen Browser Dev-Tools prüfen. 

Vermutlich wird es wirklich ein Caching Problem sein, dass die API Response von pr0 Zeit x gecached wird. Kann ich mir mal anschauen und weiterleiten, aber ich kann darauf keinen Einfluss nehmen. Wenn du nochmal eine Nachricht bekommen solltest, warte doch mal ein paar Minuten und schau ob sie dann auftaucht.

**Comment by twobiers** [comment]
Hmm okay ich kann es reproduzieren und es scheint nicht von der API zu kommen. Ich schau es mir nochmal an.
